name : Say Hello

on:
    push:
        branches:
            - main
jobs:
    hello_world:
        runs-on: ubuntu-20.04 # Podríamos haber puesto ubuntu-latest
        steps:
            - name: Echo the message
              run: 
                    echo "Hola Equipo!"
